# Generated by Django 5.1.3 on 2026-03-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBA_Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('endpoint_api', models.URLField()),
            ],
        ),
    ]
