# Generated by Django 5.1.3 on 2026-03-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('transportistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBA_Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado_actual', models.CharField(choices=[('registrado', 'Registrado'), ('en_transito', 'En Tránsito'), ('centro_distribucion', 'Centro de Distribución'), ('en_reparto', 'En Reparto'), ('entregado', 'Entregado'), ('incidente', 'Incidente')], default='registrado', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cba_cliente')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportistas.cba_transportista')),
            ],
        ),
    ]
