# Generated by Django 5.1.3 on 2026-03-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBA_TrackingEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
